### ISSUE TITLE
Implement the tip list page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#22]
- [x] #23 Create tip collection and save tip to it
- [x] #24 Create the restful api to serve tips list
- [x] #25 Create the tips table
- [x] #26 Implement the identity component
- [x] #46 Handle historical tips with same hash
- [x] #47 Show finder and beneficiary's identity where existed
- [x] #64 Handle treasury tip calls by proxy module
